/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Antropik (https://sketchfab.com/Antropik)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/astronaut-482bf87662fd4b378bcb3a2931d59ca3
Title: astronaut
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Astronaut(props) {
  const group = useRef()

  const { nodes, materials, animations } = useGLTF('/models/astronaut(1).glb')
  const { actions, names } = useAnimations(animations, group)

  useEffect(() => {
    if (actions && names.length > 0) {
      // Play the first available animation
      actions[names[0]].play()
    }
  }, [actions, names])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="3d45031c62534d44b6da04e2afe6a28cfbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="jacket" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="helmet" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="metarig" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <group name="Object_7">
                    <primitive object={nodes._rootJoint} />
                    <skinnedMesh
                      castShadow
                      receiveShadow
                      name="Object_10"
                      geometry={nodes.Object_10.geometry}
                      material={materials.astronaut}
                      skeleton={nodes.Object_10.skeleton}
                    />
                    <skinnedMesh
                      castShadow
                      receiveShadow
                      name="Object_12"
                      geometry={nodes.Object_12.geometry}
                      material={materials.astronaut}
                      skeleton={nodes.Object_12.skeleton}
                    />
                    <skinnedMesh
                     castShadow
                      receiveShadow
                      name="Object_122"
                      geometry={nodes.Object_122.geometry}
                      material={materials.astronaut}
                      skeleton={nodes.Object_122.skeleton}
                    />
                    <skinnedMesh
                     castShadow
                      receiveShadow
                      name="Object_124"
                      geometry={nodes.Object_124.geometry}
                      material={materials.astronaut}
                      skeleton={nodes.Object_124.skeleton}
                      morphTargetDictionary={nodes.Object_124.morphTargetDictionary}
                      morphTargetInfluences={nodes.Object_124.morphTargetInfluences}
                    />
                    <group name="Object_9" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_11" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_121" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_123" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                  </group>
                </group>
                <group name="jacket001" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="glass001" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group
                  name="Empty"
                  position={[189.179, 169.746, -108.207]}
                  rotation={[0, -Math.PI / 2, 0]}
                  scale={81.833}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/astronaut(1).glb')