/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Medhatelo (https://sketchfab.com/Medhatelo)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/astronaut-helmet-315605194a474c7b95cd2a9083985d22
Title: Astronaut Helmet
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function AstronautHelmet(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/astronaut_helmet.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="a2eefb9d0a4e4991b57f5b2f76730531fbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group
                  name="Helmet-Body"
                  position={[-0.177, 20.789, 0.06]}
                  rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh
                    name="Helmet-Body_Helmet-Body_0"
                    castShadow
                    receiveShadow
                    geometry={nodes['Helmet-Body_Helmet-Body_0'].geometry}
                    material={materials['Helmet-Body']}
                  />
                  <mesh
                    name="Helmet-Body_helmet_glass_0"
                    castShadow
                    receiveShadow
                    geometry={nodes['Helmet-Body_helmet_glass_0'].geometry}
                    material={materials.helmet_glass}
                  />
                  <group name="Black-one" position={[0, -3.421, -1.917]} rotation={[-1.82, 0, 0]}>
                    <group name="Object_8" position={[0, -0.185, -0.149]}>
                      <mesh
                        name="Black-one_Standard_14_0"
                        castShadow
                        receiveShadow
                        geometry={nodes['Black-one_Standard_14_0'].geometry}
                        material={materials.Standard_14}
                      />
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/astronaut_helmet.glb')

