/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: SebastianSosnowski (https://sketchfab.com/SebastianSosnowski)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/earth-4de1bcbd22a444abb4f089b9b78ec96a
Title: Earth
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export function Earth6(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/earth(3)_compressed(1).glb')
  const { actions } = useAnimations(animations, group)

  useFrame((state) => {
        group.current.rotation.y = state.clock.getElapsedTime() * 0.005
        return(() => group.current.rotation.y = 0)
    });

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="3f0d8c1a7c7c45138e5b99b56838fcb9fbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Earth" rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh
                    name="Earth_Material_#50_0"
                    castShadow
                    receiveShadow
                    geometry={nodes['Earth_Material_#50_0'].geometry}
                    material={materials.Material_50}
                  />
                </group>
                <group name="EarthClouds" rotation={[-Math.PI / 2, -Math.PI / 9, 0]} scale={1.01}>
                  <mesh
                    name="EarthClouds_Material_#62_0"
                    castShadow
                    receiveShadow
                    geometry={nodes['EarthClouds_Material_#62_0'].geometry}
                    material={materials.Material_62}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/earth(3)_compressed(1).glb')

