/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: ABOD.ANIMATION (https://sketchfab.com/body3d2005)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/earth-c2e4294c32ea4d8b850e152fc26aeeb4
Title: earth
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'


   

export function Earth6(props) {
  const { nodes, materials } = useGLTF('/models/earth(2).compressed.glb')
  
  const earthRef = useRef()   
      // useFrame((state) => {
      useFrame(() => {
          // earthRef.current.rotation.x = state.clock.getElapsedTime() * 0.005
          earthRef.current.rotation.x += 0.00009
          return(() => earthRef.current.rotation.x = 0)
      });
  
  return (
    <group ref={earthRef} {...props} dispose={null}>
      <group scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sphere_Material001_0.geometry}
          material={materials['Material.001']}
          rotation={[-Math.PI / 2, 0, -0.262]}
          scale={100}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/earth(2).compressed.glb')

