/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Patrick Matthew (https://sketchfab.com/patrickmatthew)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/earth-3827e559d4f34387b6757b63678c069b
Title: Earth
*/

import React, { useRef } from 'react'
// import { useGLTF, useAnimations } from '@react-three/drei'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export function Earth1(props) {
  const earthAtmosphereRef = useRef()
  const earthSphereRef = useRef()
  // const { nodes, materials, animations } = useGLTF('/models/earth(1).glb')
  const { nodes, materials } = useGLTF('/models/earth(1).glb')
  // const { actions } = useAnimations(animations, earthAtmosphereRef)

  useFrame(() => {
    earthAtmosphereRef.current.rotation.y += 0.0001
    earthSphereRef.current.rotation.y += 0.0001
  })
  return (
    <group {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={574.179}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Earth_0">
                <mesh
                  ref={earthAtmosphereRef}
                  name="Object_4"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_4.geometry}
                  material={materials.earth}
                />
              </group>
              <group name="Clouds_1">
                <mesh
                  ref={earthSphereRef}
                  name="Object_6"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_6.geometry}
                  material={materials.clouds}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/earth(1).glb')