/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: SebastianSosnowski (https://sketchfab.com/SebastianSosnowski)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/moon-petavius-crater-ce9c009b517b421eab8c8429b536382f
Title: Moon - Petavius crater
*/

import { useGLTF } from '@react-three/drei'

export function Moon(props) {
  const { nodes, materials } = useGLTF('/models/moon_-_petavius_crater_optimized.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={1.17}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Petavius_ZB_LP_1_0.geometry}
          material={materials.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Petavius_ZB_LP_2_0.geometry}
          material={materials.material_1}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/moon_-_petavius_crater_optimized.glb')