/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: SebastianSosnowski (https://sketchfab.com/SebastianSosnowski)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/tsiolkovskiy-crater-on-the-moon-ca-180km-diam-185cccfa4b8d4b228bbf3277cf798b7a
Title: Tsiolkovskiy crater on the Moon (ca 180km diam.)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function MoonCrater(props) {
  const { nodes, materials } = useGLTF('/models/tsiolkovskiy_crater_on_the_moon_ca_180km_diam..glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tsiolkovskiy_LP_2_0.geometry}
          material={materials.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Tsiolkovskiy_LP_Material_#64_0'].geometry}
          material={materials.Material_64}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/tsiolkovskiy_crater_on_the_moon_ca_180km_diam..glb')