/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: ul1tka (https://sketchfab.com/ul1tka)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sci-fi-crate-ammunition-box-2-342efe4d70f94d37a4edd66a15c39502
Title: Sci-Fi crate / ammunition box (2)
*/

import { useGLTF } from '@react-three/drei'

export function SciFiAmmunitionBox2(props) {
  const { nodes, materials } = useGLTF('/models/sci-fi_crate__ammunition_box_2_optimized.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_low_Box2_0.geometry}
          material={materials.Box2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Slice001_low_Box2_0.geometry}
          material={materials.Box2}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Slice_low_Box2_0.geometry}
        material={materials.Box2}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube001_low_Box2_0.geometry}
        material={materials.Box2}
        position={[0, 0, 12.92]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002_low_Box2_0.geometry}
        material={materials.Box2}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube003_low_Box2_0.geometry}
        material={materials.Box2}
        position={[0, -3.098, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube1_low_Box2_0.geometry}
        material={materials.Box2}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
    </group>
  )
}

useGLTF.preload('/models/sci-fi_crate__ammunition_box_2_optimized.glb')