/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: JazOone (https://sketchfab.com/JazOone)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sci-fi-compact-radar-6a81f881ec3d4f11b45c4bdf32f30f8c
Title: Sci-fi Compact-Radar
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function SciFiRadar(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/sci-fi_compact-radar.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={0.119}>
          <group name="Sci-fi_Compact-Radarfbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Cylinder" position={[0.304, -60.53, 18.67]} />
                <group name="Compact_Radar" rotation={[-Math.PI / 2, 0, 0]} scale={463.242}>
                  <group name="Object_6">
                    <primitive object={nodes._rootJoint} />
                    <skinnedMesh
                      name="Object_9"
                      geometry={nodes.Object_9.geometry}
                      material={materials['Material.001']}
                      skeleton={nodes.Object_9.skeleton}
                    />
                    <group name="Object_8" position={[0.304, -60.53, 18.67]} />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/sci-fi_compact-radar.glb')