/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Sousinho (https://sketchfab.com/sousinho)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/futuristic-scifi-style-small-tableboxes-4c2cd410b666428a8254f224488f38dc
Title: Futuristic scifi style small table/boxes
*/

import { useGLTF } from '@react-three/drei'

export function SciFiBoxes(props) {
  const { nodes, materials } = useGLTF('/models/futuristic_scifi_style_small_tableboxes_optimized.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SM_Side_tables002_T_SideBoxes_0.geometry}
          material={materials.T_SideBoxes}
          position={[341.343, -185.149, 513.579]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SM_Side_tables001_T_SideBoxes_0.geometry}
          material={materials.T_SideBoxes}
          position={[337.465, -185.149, 513.579]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SM_Side_tables003_T_SideBoxes_0.geometry}
          material={materials.T_SideBoxes}
          position={[234.814, -183.093, 514.302]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/futuristic_scifi_style_small_tableboxes_optimized.glb')

