/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: ul1tka (https://sketchfab.com/ul1tka)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sci-fi-crate-ammunition-box-1-69fe3211493c4a4db26ad0c4e2e49a83
Title: Sci-Fi crate / ammunition box (1)
*/

import { useGLTF } from '@react-three/drei'

export function SciFiAmmunitionBox(props) {
  const { nodes, materials } = useGLTF('/models/sci-fi_crate__ammunition_box_1_optimized.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube_low_base_0.geometry}
        material={materials.base}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube001_low_base_0.geometry}
        material={materials.base}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube006_low_base_0.geometry}
        material={materials.base}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube003_low_base_0.geometry}
        material={materials.base}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box_low_base_0.geometry}
        material={materials.base}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box001_Curve_low_base_0.geometry}
        material={materials.base}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box2_low_base_0.geometry}
        material={materials.base}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube005_low_base_0.geometry}
        material={materials.base}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube004_low_base_0.geometry}
        material={materials.base}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002_low_base_0.geometry}
        material={materials.base}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
    </group>
  )
}

useGLTF.preload('/models/sci-fi_crate__ammunition_box_1_optimized.glb')