/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Sousinho (https://sketchfab.com/sousinho)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/scifi-box-252e8ba19173443395d86c5ff888a3b7
Title: Scifi Box
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function SciFiSafeBox(props) {
  const { nodes, materials } = useGLTF('/models/scifi_box.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_4.geometry}
        material={materials['ZenUV_Generic_Material.007']}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  )
}

useGLTF.preload('/models/scifi_box.glb')