/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: holgcool (https://sketchfab.com/holgcool)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sci-fi-laptop-alternative-90s-1d67104ac71c495293fdbf7e7059b732
Title: Sci Fi Laptop alternative 90s
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function SciFiLaptop(props) {
  const { nodes, materials } = useGLTF('/models/sci_fi_laptop_alternative_90s.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Laptop_Export_����������������003_0'].geometry}
          material={materials['.003']}
          position={[66.6, -5, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/sci_fi_laptop_alternative_90s.glb')