/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: AjaxGb (https://sketchfab.com/ajaxgb)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/extracted-minecraft-java-editions-stars-c8868b7ffc4a473eb5cd9203a59e3650
Title: [Extracted] Minecraft Java Edition's Stars
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export function Stars(props) {
  const starsRef = useRef()
  const { nodes, materials } = useGLTF('/models/extracted_minecraft_java_editions_stars.glb')
  
  useFrame(() => {
    starsRef.current.rotation.y += 0.0001
  })
  return (
    <group ref={starsRef} {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_2.geometry}
        material={materials.star}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  )
}

useGLTF.preload('/models/extracted_minecraft_java_editions_stars.glb')

