/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: VIS-All-3D (https://sketchfab.com/VIS-All)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/simple-sun-83dd341b8c4c4f83808f5821e89f056e
Title: Simple Sun
*/

import React
// , { useRef } 
from 'react'
import { useGLTF } from '@react-three/drei'

export function Sun2(props) {
  const { nodes, materials } = useGLTF('/models/sun.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        // castShadow
        // receiveShadow
        geometry={nodes.Sphere_0.geometry}
        material={materials['Scene_-_Root']}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  )
}

useGLTF.preload('/models/sun.glb')
